baseURL = "https://samuelwangg.github.io/"
languageCode = "en-us"
title = "Thoughts"
theme = "qnd"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength=20

[params]
  description = "Samuel's Personal Blog"
  highlight = true
    [[params.socialIcons]]
      name = "rss"
      url = "https://samuelwangg.github.io/posts/index.xml"
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/samuelwangg"
    [[params.socialIcons]]
      name = "linkedin"
      url = "https://www.linkedin.com/in/samuelwang0/"
    [[params.socialIcons]]
      name = "email"
      url = "mailto:samuel.wang@hotmail.ca"
    [[params.socialIcons]]
      name = "instagram"
      url = "https://www.instagram.com/samvelwang/"

[menu]
  [[menu.main]]
    identifier = "ideas"
    name = "ideas"
    title = "ideas"
    url = "/ideas/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true